# Generated by Django 5.1.4 on 2024-12-23 23:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='Pagina',
        ),
        migrations.RenameField(
            model_name='pagina',
            old_name='content',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='pagina',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='pagina',
            old_name='subtitle',
            new_name='subtitulo',
        ),
        migrations.RenameField(
            model_name='pagina',
            old_name='title',
            new_name='titulo',
        ),
    ]
