# Generated by Django 5.1.4 on 2024-12-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0004_page_delete_pagina'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='categoria',
            field=models.CharField(choices=[('pantalones', 'Pantalones'), ('buzos', 'Buzos'), ('remeras', 'Remeras')], default='remeras', max_length=20),
        ),
    ]
