# Generated by Django 5.1.4 on 2024-12-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0007_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
