# Generated by Django 5.1.4 on 2024-12-27 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0008_alter_cartitem_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(default='Descripción por defecto'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='page',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_coder.categoria'),
        ),
        migrations.AlterField(
            model_name='page',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_pagina/'),
        ),
    ]
